---
name: unit-tests

run-name: Unit tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "iac/**/*_test.go"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  unit_tests_in_iac:
    name: Unit tests in iac
    runs-on: ubuntu-latest
    needs: skip-duplicate-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go latest
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies for iac/plm/util
        run: go mod download
        working-directory: iac/plm/util

      - name: Run unit tests on Pulumi functions in iac/plm/util
        run: go test -v ./...
        working-directory: iac/plm/util

      - name: Download dependencies for iac/plm
        run: go mod download
        working-directory: iac/plm

      - name: Run unit tests on Pulumi functions in iac/plm
        run: go test -v .
        working-directory: iac/plm
